services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: finance
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d finance" ]
      interval: 5s
      timeout: 5s
      retries: 5

  db-init:
    image: postgres:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["true"]

  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: budgetsite.settings
      CORS_ORIGIN_WHITELIST: "http://localhost:3000,http://127.0.0.1:3000"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c "
        python manage.py migrate --no-input &&
        gunicorn budgetsite.wsgi:application --bind 0.0.0.0:8000
      "
    # Убедись, что нет конфликтов с командой в startup.sh

volumes:
  postgres_data:
